### ISSUE TITLE
STARTMAP problems with interpret

### ISSUE THREAD

**Issue by lnlyssg** [mainframed/Enumeration#14]
Still trying to figure this out and I hope I can fix it myself but...

An LPAR I’m currently looking at has some entries in IEASYM00 with underscores e.g.:
`SYMDEF(&LOG_=‘INITPARM(‘’xxxx’’)’)`

but the interpret function doesn’t like the “_”. If I skip that line I have a second issue further on with a symbol that resolves to ‘+++++’ which interpret also complains about...

**Comment by mainframed** [comment]
Which line is doing the interpret?

**Comment by lnlyssg** [comment]
Line 83 `interpret NAMED||"="||VALNAME `
