### ISSUE TITLE
In ENUM exec the column headers for USSU are out of order?

### ISSUE THREAD

**Issue by travatine** [mainframed/Enumeration#17]
Hi,

We noticed that the UID and GID columns appear in incorrect order.
This line appears to be the issue:

` usr.ucount = left(Name,8) left(UID,10) left(GID,10) left(Home, 48)   `

it should be:

` usr.ucount = left(Name,8) left(GID,10) left(UID,10) left(Home, 48)   `

so the GID appears after uid.

Thanks!

**Comment by mainframed** [comment]
NICE CATCH! Do you mind making a pull request?
