### ISSUE TITLE
ENUM-carrying "NO" in EXISTS field

### ISSUE THREAD

**Issue by bigendiansmalls** [mainframed/Enumeration#5]
## Steps to reproduce
- [ ] Run ENUM APF
![before](https://user-images.githubusercontent.com/13771080/31963430-3809f9f2-b8c6-11e7-8359-6d5d676d1883.png)
- [ ] Delete one of the datasets - here 'FEU.Z21F.LINKLIB'
- [ ] Re-run  ENUM APF
- [ ] Note all APF libraries after deleted one are incorrectly listed as NO under EXISTS
![after](https://user-images.githubusercontent.com/13771080/31963434-3bbccd22-b8c6-11e7-91e5-007e9883c55e.png)

**Comment by lnlyssg** [comment]
When you say delete the dataset I assume you mean actually deleting it but still leaving it as APF-authed?

Also, utterly unrelated to the issue but looking at the screenshots - do the latest ADCD images have zSecure available?

**Comment by lnlyssg** [comment]
@bigendiansmalls Right, should be fixed but I can't actually test it right now. Let me know if it works OK!

**Comment by bigendiansmalls** [comment]
Correct.  Just delete the dataset, not messing with the actual APF list.

On Oct 24, 2017, at 14:52, Jim <notifications@github.com<mailto:notifications@github.com>> wrote:


When you say delete the dataset I assume you mean actually deleting it but still leaving it as APF-authed?

Also, utterly unrelated to the issue but looking at the screenshots - do the latest ADCD images have zSecure available?

**Comment by bigendiansmalls** [comment]
Will retest tonight.  Thanks.

On Oct 24, 2017, at 15:14, Jim <notifications@github.com<mailto:notifications@github.com>> wrote:


@bigendiansmalls<https://github.com/bigendiansmalls> Right, should be fixed but I can't actually test it right now. Let me know if it works OK!

**Comment by bigendiansmalls** [comment]
@jaytay79 Confirmed fixed.  Cheers.

**Comment by mainframed** [comment]
Awesome.
